### ISSUE TITLE
aRchive currently empty?

### ISSUE THREAD

**Issue by peterjc** [bioarchive/aRchive_source_code#3]
http://bioarchive.github.io/ has a big green button "Access the aRchive documents here" linking to http://bioarchive.s3-website-us-east-1.amazonaws.com/ which appears to be empty bar `bucket_index.html` (which lists no sub-content) and `log.txt`

**Comment by nturaga** [comment]
Will be up and running in a day or two.

**Comment by peterjc** [comment]
Looks like there is some content now :)

P.S. Perhaps black list `.DS_Store` from being included?

**Comment by nturaga** [comment]
Hi!  I was going to close it later on today, the upload was taking a while on to the s3 bucket. Yes, the bucket needs a little refinement. Will be working on it this weekend.
