### ISSUE TITLE
bioconductor package GenomeInfoDbData not available

### ISSUE THREAD

**Issue by dlaehnemann** [bioarchive/aRchive_source_code#38]
Hi,

due to an installation problem of this package over at bioconda, I realized that the [bioconductor package `GenomeInfoDbData`](https://bioconductor.org/packages/3.13/data/annotation/html/GenomeInfoDbData.html) is not available here in `bioarchive`. In particular, this link leads nowhere:

https://github.com/bioconda/bioconda-recipes/blob/2b33feeddaf202e214432f0ca8d31d53d0c17868/recipes/bioconductor-genomeinfodbdata/meta.yaml#L11

I have tested it for version 1.2.6 (and someone else [also described this](https://github.com/bioconda/bioconda-recipes/issues/28801)):

* https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.6.tar.gz

And it has previously been described for version 1.2.4:
https://github.com/bioconda/bioconda-recipes/issues/26657

I have no clue how bioarchive works, but figured I'd write an issue here, as its the only repo I have found. If I'm wrong, I'd be glad for pointers where to post this.

Thanks a bunch,
david

**Comment by nturaga** [comment]
This is probably better addressed on the Bioconda channel.

**Comment by dlaehnemann** [comment]
Sure, the link can simply be removed there. But I would have thought that the package should also be available on bioaRchive via this link, as previous versions were also available and current versions of related packages are. Or are bioaRchive or some packages on it no longer maintained? I guess I am missing some part of the picture, here?

**Comment by dlaehnemann** [comment]
I guess this explains, why the bioarchive package isn't there:
https://github.com/bioconda/bioconda-recipes/pull/23728#issuecomment-668663952
