### ISSUE TITLE
Mention http://bioarchive.github.io/ in README

### ISSUE THREAD

**Issue by peterjc** [bioarchive/aRchive_source_code#5]
It is unclear from the README alone what the project is about - the repository description (as viewed on GitHub) includes the key link http://bioarchive.github.io/ which could be added to the README file as well.

**Comment by nturaga** [comment]
README fixed via [849a8c7](https://github.com/bioarchive/aRchive_source_code/commit/d5b5b8415b9324a52019b6db48cc3b4150ab5f97)

**Comment by sbliven** [comment]
The linked commit didn't actually address this issue. See also #17
