### ISSUE TITLE
Jenkins vs cron

### ISSUE THREAD

**Issue by nturaga** [bioarchive/aRchive_source_code#7]
Need to move this to a remote machine, and run it once/twice a week.

**Comment by hexylena** [comment]
[IUC Jenkins](http://gx.hx42.org/) machine is happy to be of service there!

**Comment by hexylena** [comment]
http://gx.hx42.org/job/bioaRchive/ make all of the .tar.gzs available once it builds correctly.

**Comment by hexylena** [comment]
You can close this now :)
