### ISSUE TITLE
yaml parser in python

### ISSUE THREAD

**Issue by nturaga** [bioarchive/aRchive_source_code#8]
Most DESCRIPTION files have tabs "\t" in them which makes the yaml.load() to raise an error and skip the version of the package.

NOTE: This is an issue in the improved code, NOT reflected in the existing aRchive. The aRchive is just fine.
<pre><code>
Updating to rev r93806
while scanning for the next token
found character '\t' that cannot start any token
  in "/Users/galaxy/Documents/Bioconductor-Rpacks/Rpacks/flowStats/DESCRIPTION", line 13, column 1
</pre></code>

**Comment by nturaga** [comment]
Test with "flowUtils" package.

**Comment by hexylena** [comment]
Oooh. Did not notice this, yeah, we'll definitely have to switch back to your older hacky parser.

**Comment by nturaga** [comment]
Switched back with commit  [451c1860fe953ca7e94283e09bab22fe245d3b77](https://github.com/bioarchive/aRchive_source_code/commit/451c1860fe953ca7e94283e09bab22fe245d3b77)

**Comment by hexylena** [comment]
+1
