### ISSUE TITLE
add code to tar up each version

### ISSUE THREAD

**Issue by hexylena** [bioarchive/aRchive_source_code#9]

**Comment by hexylena** [comment]
Side note, when this gets done...the (latest?) tars maybe should go in 

`/src/contrib/$package.tgz`

so that the following will be functional:

`install.packages("limma", repos="http://bioarchive.s3-website-us-east-1.amazonaws.com/", type="source")`

**Comment by nturaga** [comment]
@erasche I'll have to ask you more about this once I get them tarfiles up. But as I understand it, you are saying, we need the archive structure to be like ?? 

`limma

 ----- limma_1.0.0.tar.gz 

 -----limma_2.0.0.tar.gz`

**Comment by hexylena** [comment]
@nitesh1989 I'm saying that it's great if the structure is

```
lima
--/limma_1.0.0.tar.gz
--/limma_2.0.0.tar.gz
```

as that will be clean/easy/useful in galaxy (which is the primary goal still).

However, if we reorganise it to

```
/src/
--/contrib/
    --/limma_1.0.0.tar.gz
    --/limma_2.0.0.tar.gz
    --/other_package.version.tar.gz
```

Then people will be able to use this from inside R with 

``` R
install.packages("limma", repos="http://bioarchive.s3-website-us-east-1.amazonaws.com/", type="source")
```

Got the idea from http://stackoverflow.com/a/1474359 and the linked repo used in that command.

**Comment by hexylena** [comment]
And people will still be able to 

``` R
install.packages("http://bioarchive.s3-website-us-east-1.amazonaws.com/src/contrib/limma_1.0.0.tar.gz", repo=NULL, type="source")
```

to get older versions

**Comment by nturaga** [comment]
Awesome @erasche .Will keep you posted.

**Comment by nturaga** [comment]
tar.gz-ed and ready to go!
